### ISSUE TITLE
mediaplayer.prepareAsync

### ISSUE THREAD

**Issue by wy353208214** [danylovolokh/VideoPlayerManager#9]
hi danylovolokh,
     In consideration of the asynchronous, VideoViewPlayer called prepare(), i want to use prepareAsync() and add a callback.
BTW:I think you can put the Features on the schedule. Thx~ -.0

**Comment by danylovolokh** [comment]
"Preparing" might take a lot of time, that's why MediaPlayer.class has this prepareAsync() so that you can call it from UI thread.
Bu there is no need for prepareAsync() because every call to the MediaPlayer.class is done in separate thread. 

There is an option of getting onPrepared() call:

mVideoPlayer.addMediaPlayerListener(new SimpleMainThreadMediaPlayerListener(){
            @Override
            public void onVideoPreparedMainThread() {

            }
        });
